writing the code of services section
GSG-FC02/real-estate-wibsite-6 pull request #2
Opened 2021-03-01 17:58 UTC by ahmadfarid-059

Rlates #1
writing the code of services section

2021-03-02 17:03 UTC, Noorin99 approved these changes, later dismissed

2021-03-04 00:16 UTC, AlaaTaima commented on style.css
> +}
**update the width here to `80%`**
```suggestion
.descriptive_paragraph{
    color: #071144;
    font-size: 15px;
    
    width: 80%;

    text-align: center;
    
    
}
```

2021-03-04 00:21 UTC, AlaaTaima commented on style.css
> +}
**update the style here as the following to enhance the final results :** 
```suggestion
.divs{
    display: flex;
    flex-direction : column;
    justify-content: space-around;
    align-items: center;
    height: 85vh;
    padding: 30px 0px;
}
```

2021-03-04 00:23 UTC, AlaaTaima commented on style.css
> +    }
**Remove `width` :** 
```suggestion
    .descriptive_paragraph{
        text-align: center;
    }
```

2021-03-04 00:25 UTC, AlaaTaima commented on style.css
> +    }
**`display:flex` has already taken so, just you have to add the property `flex-direction`** 
```suggestion
    .main_div{
        flex-direction: column;
        height: auto;

    }
```

2021-03-04 00:35 UTC, AlaaTaima commented on style.css
> +}
**Remove the default border of the button by using `border : none`** 

```suggestion
.button{
    width: 180px;
    height: 50px;
    border-radius: 15%;
    background-color: #0f4b5e;
    color: white;
    font-size: 20px;
    font-weight: lighter;
    margin-top: 10px;
    border : none;

}
```

2021-03-04 00:36 UTC, AlaaTaima commented on style.css
> +}
change the mouse shape to pointer by using `cursor: pointer;`
```suggestion
.button:hover{
    background-color: white;
    color: cornflowerblue;
        cursor : pointer;

}
```

2021-03-04 00:41 UTC, AlaaTaima commented on style.css
> +}
**No need for this query , delete it**

2021-03-04 00:43 UTC, AlaaTaima commented on style.css
> +}
**Add a `width : 100%` to the title style here :** 
```suggestion
.title{
    margin: 20px;
    color: #071144;
    padding-top: 15px;
    font-weight: bold;
    width : 100%;

    
}
```

2021-03-04 00:47 UTC, AlaaTaima commented on style.css
> +}
**Fix the selector here :** 
```suggestion
a {
    text-decoration: none;
}
```

2021-03-04 01:05 UTC, AlaaTaima requested changes
**Good Job 👍** 

**But, there are some points that would be awesome to get enhanced.**

2021-03-04 14:13 UTC, AlaaTaima approved these changes

2021-03-04 14:13 UTC, merged