writing html and css code for footer in home page
GSG-FC02/real-estate-wibsite-6 pull request #4
Opened 2021-03-02 08:56 UTC by ahmedsinwar

Relates #2

2021-03-03 17:13 UTC, Noorin99 submitted a review, later dismissed

2021-03-03 23:51 UTC, AlaaTaima commented on Footer.html
> +        <div class="footer">
**Use the semantic element `footer` here instead of `div`** 
```suggestion
        <footer class="footer">
```

2021-03-03 23:52 UTC, AlaaTaima commented on footer.css
> +}
**I see, there is no need for this `media query`** 

**So, delete it**

2021-03-03 23:53 UTC, AlaaTaima requested changes
**Good job @ahmedsinwar  👍** 

**But, there are some points that would be awesome to get enhanced.**

2021-03-04 07:39 UTC, ahmadfarid-059 approved these changes
Approved after Alaa's changes

2021-03-04 10:43 UTC, AlaaTaima approved these changes

2021-03-04 10:44 UTC, merged