Adding Profile picture and a search bar
GSG-FC02/real-estate-wibsite-6 pull request #7
Opened 2021-03-02 09:11 UTC by Noorin99

Relates #5

2021-03-03 17:14 UTC, ahmedsinwar submitted a review, later dismissed

2021-03-03 21:35 UTC, AlaaTaima commented on style.css
> +@media screen and (max-width: 375px){
change the screen width here to `425 px` to fix `font-size` at the screen that it's width 
```suggestion
@media screen and (max-width: 425px){
```
between ` 0 px - 425 px `

2021-03-03 21:45 UTC, AlaaTaima commented on style.css
> +}
here, you can it's better to update the style as the following : 

* use short syntax for `padding`
* to center the 2-buttons you can use just `justify-content : center` and delete `text-align` & `padding-left` that have no-effect. 
```suggestion
.main_container_list{
    list-style: none;
    padding: 20px 0px;
    display: flex;
    justify-content: center;	
}
```

2021-03-03 21:54 UTC, AlaaTaima commented on style.css
> +}
here, it's better to update the style as the following : 

* use short syntax for `padding`
* to center the 2-buttons you can use just `justify-content : space-around` and `margin : 0 auto ` then delete  `text-align` & `padding-left` that have no-effect. 
* make the width of  the list : `50%`
* delete `padding-left : 20px` from the class `.main_container_list_botton`
```suggestion
.main_container_list{
	.main_container_list{
    list-style: none;
    padding: 20px 0px;
    display: flex;
    justify-content: space-around;	
    width : 50%
}

.main_container_list_botton{
	border: none;
	background: unset;
	font-size: 16px;	
}
```

2021-03-03 22:13 UTC, AlaaTaima commented on style.css
> +}
update the style here at the media query here to fix the buttons style at this width : 

```suggestion
	.main_container_list{
		width : 100%;
	
}
```

2021-03-03 22:16 UTC, AlaaTaima commented on style.css
> +}
here, add a property to change the mouse shape to a pointer when hover on the button : 
 
```suggestion
.main_container_list_botton:hover{
	background: white;
	font-size: 17px;
	font-weight: bold;
	color: #4fb8d5;
	cursor: pointer;

}
```

2021-03-03 22:22 UTC, AlaaTaima commented on style.css
> +}
**Use the class selector instead of the tag itself :** 

```suggestion
.main_container_search {
	display: flex;

}
```

2021-03-03 22:23 UTC, AlaaTaima commented on style.css
> +}
**Fix the selector here as the following :** 
```suggestion
.main_container_search button{
	height: 30px;
	width: 30px;
	border: 2px solid #071144;
	background: #071144;
	color: white;
}
```

2021-03-03 23:16 UTC, AlaaTaima requested changes
**Good Job Nour 👍** 

**But, There are some points that would be awesome to get enhanced.**

2021-03-04 07:38 UTC, ahmadfarid-059 submitted a review, later dismissed
Approved with Alaa's changes

2021-03-04 11:49 UTC, AlaaTaima approved these changes

2021-03-04 11:49 UTC, merged